server:
    port: 8081
spring:
  application:
    name: chl-msa-current-account


  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: "classpath:db/migration"
    sql-migration-suffixes: ".sql"
    sql-migration-prefix: V
    sql-migration-separator: "__"
    url: jdbc:postgresql://localhost:3540/postgres
    user: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:password}
    schemas: ${POSTGRESQL_SCHEMA:challenge}

challenge:
  postgresql:
    host: ${ONB_POSTGRESQL_HOST:localhost}
    port: ${ONB_POSTGRESQL_PORT:3540}
    dbname: ${POSTGRESQL_DBNAME:postgres}
    schema: ${POSTGRESQL_SCHEMA:challenge}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:password}
    ssl-mode: ${POSTGRESQL_SSL:disable}
  connect-timeout: ${CONNECT_TIMEOUT:30000}
  read-timeout: ${READ_TIMEOUT:30000}
  max-in-memory-size: ${MAX_IN_MEMORY_SIZE:41943040}
  services:
    customer:
      base-url: ${SERVICE_CUSTOMER_BASE_URL:http://localhost:8080/api/v1}
      get-identification-path: ${SERVICE_CUSTOMER_GET_IDENTIFICATION_PATH:/customers}

logging:
  level:
    org.flywaydb: DEBUG
